export { BackupPlan, enableBackups, tagDynamoDBTableAsCompliant } from './tags'
export { compliantBucketProps, Bucket } from './s3'
export { compliantKeyProps, Key } from './kms'
export { TopicProps, Topic } from './sns'
export { Table } from './dynamodb'
export { BehaviorOptions, defaultDistributionProps, Distribution, DistributionProps } from './cloudfront'
export { defaultQueueProps, QueueProps, Queue } from './sqs'
